### ISSUE TITLE
http://docker.sh/ip is down

### ISSUE THREAD

**Issue by kubenstein** [mcuadros/dockership#21]
hi,
i starred this project because it may be exactly what i need, but it looks like http://docker.sh/ip is not reachable at this mom. im sure few days ago everything was ok.
cheers!

**Comment by mcuadros** [comment]
Really sorry the site is hosted on a digitalocean and due to the low activity looks like is getting the process in background and I dont know why. I need move this to another place.

**Comment by kubenstein** [comment]
Thank you so much, im gonna try the project. if page is pure static maybe you can host it on github or heroku free plan?
